apiVersion: v1
kind: Secret
metadata:
  name: audit-service-secrets
  namespace: audit-service
  labels:
    app.kubernetes.io/name: audit-service
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # JWT Secret Key (should be generated and stored securely)
  JWT_SECRET_KEY: "your-super-secret-jwt-key-change-this-in-production"
  
  # Database Connection (will be populated by Terraform outputs)
  DATABASE_URL: "postgresql://audit_user:password@postgres-service:5432/audit_db"
  
  # BigQuery Service Account Key (JSON format)
  GOOGLE_APPLICATION_CREDENTIALS_JSON: |
    {
      "type": "service_account",
      "project_id": "your-project-id",
      "private_key_id": "key-id",
      "private_key": "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY\n-----END PRIVATE KEY-----\n",
      "client_email": "audit-service@your-project-id.iam.gserviceaccount.com",
      "client_id": "client-id",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/audit-service%40your-project-id.iam.gserviceaccount.com"
    }
  
  # GCP Project Configuration
  GCP_PROJECT_ID: "your-project-id"
  GCP_REGION: "us-central1"
  
  # Redis Password (if authentication is enabled)
  REDIS_PASSWORD: ""
  
  # API Keys for external services
  EXTERNAL_API_KEY: "your-external-api-key"
  
  # Encryption keys for sensitive data
  ENCRYPTION_KEY: "your-32-character-encryption-key"
  
  # Database credentials for fallback PostgreSQL
  POSTGRES_USER: "audit_user"
  POSTGRES_PASSWORD: "secure-password-change-this"
  POSTGRES_DB: "audit_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: audit-service-tls
  namespace: audit-service
  labels:
    app.kubernetes.io/name: audit-service
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    # Your TLS certificate here
    # This should be replaced with actual certificate from cert-manager or external CA
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    # Your TLS private key here
    # This should be replaced with actual private key
    -----END PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: audit-service-registry
  namespace: audit-service
  labels:
    app.kubernetes.io/name: audit-service
    app.kubernetes.io/component: registry
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "gcr.io": {
          "username": "_json_key",
          "password": "{\"type\":\"service_account\",\"project_id\":\"your-project-id\"}",
          "email": "audit-service@your-project-id.iam.gserviceaccount.com"
        }
      }
    }