apiVersion: v1
kind: ServiceAccount
metadata:
  name: audit-service
  namespace: audit-service
  labels:
    app.kubernetes.io/name: audit-service
    app.kubernetes.io/component: serviceaccount
  annotations:
    iam.gke.io/gcp-service-account: audit-service@PROJECT_ID.iam.gserviceaccount.com
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: audit-service
  namespace: audit-service
  labels:
    app.kubernetes.io/name: audit-service
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: audit-service
  namespace: audit-service
  labels:
    app.kubernetes.io/name: audit-service
    app.kubernetes.io/component: rbac
subjects:
- kind: ServiceAccount
  name: audit-service
  namespace: audit-service
roleRef:
  kind: Role
  name: audit-service
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: audit-service-cluster
  labels:
    app.kubernetes.io/name: audit-service
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/metrics"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: audit-service-cluster
  labels:
    app.kubernetes.io/name: audit-service
    app.kubernetes.io/component: rbac
subjects:
- kind: ServiceAccount
  name: audit-service
  namespace: audit-service
roleRef:
  kind: ClusterRole
  name: audit-service-cluster
  apiGroup: rbac.authorization.k8s.io