"""Add is_default column to llm_providers

Revision ID: 2973f30baabc
Revises: c0770f67ed65
Create Date: 2025-08-29 20:23:41.772699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2973f30baabc'
down_revision = 'c0770f67ed65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('llm_providers', sa.Column('is_default', sa.Boolean(), nullable=True))
    
    # Set default value for existing records
    op.execute("UPDATE llm_providers SET is_default = false WHERE is_default IS NULL")
    
    # Make column not nullable
    op.alter_column('llm_providers', 'is_default', nullable=False)
    
    op.create_index('idx_llm_providers_default', 'llm_providers', ['is_default'], unique=False)
    op.create_index(op.f('ix_llm_providers_is_default'), 'llm_providers', ['is_default'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_providers_is_default'), table_name='llm_providers')
    op.drop_index('idx_llm_providers_default', table_name='llm_providers')
    op.drop_column('llm_providers', 'is_default')
    # ### end Alembic commands ###