"""Add cloud_projects table

Revision ID: 7d9c05c602ef
Revises: 2973f30baabc
Create Date: 2025-08-30 22:09:17.775374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9c05c602ef'
down_revision = '2973f30baabc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_projects',
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cloud_provider', sa.String(length=50), nullable=False),
    sa.Column('project_identifier', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_subscribe', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cloud_provider IN ('gcp', 'aws', 'azure', 'oci')", name='ck_cloud_projects_provider'),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('tenant_id', 'cloud_provider', 'project_identifier', name='uq_cloud_projects_tenant_provider_identifier')
    )
    op.create_index('idx_cloud_projects_provider_enabled', 'cloud_projects', ['cloud_provider', 'enabled'], unique=False)
    op.create_index('idx_cloud_projects_tenant_enabled', 'cloud_projects', ['tenant_id', 'enabled'], unique=False)
    op.create_index(op.f('ix_cloud_projects_cloud_provider'), 'cloud_projects', ['cloud_provider'], unique=False)
    op.create_index(op.f('ix_cloud_projects_created_by'), 'cloud_projects', ['created_by'], unique=False)
    op.create_index(op.f('ix_cloud_projects_enabled'), 'cloud_projects', ['enabled'], unique=False)
    op.create_index(op.f('ix_cloud_projects_name'), 'cloud_projects', ['name'], unique=False)
    op.create_index(op.f('ix_cloud_projects_project_identifier'), 'cloud_projects', ['project_identifier'], unique=False)
    op.create_index(op.f('ix_cloud_projects_tenant_id'), 'cloud_projects', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cloud_projects_tenant_id'), table_name='cloud_projects')
    op.drop_index(op.f('ix_cloud_projects_project_identifier'), table_name='cloud_projects')
    op.drop_index(op.f('ix_cloud_projects_name'), table_name='cloud_projects')
    op.drop_index(op.f('ix_cloud_projects_enabled'), table_name='cloud_projects')
    op.drop_index(op.f('ix_cloud_projects_created_by'), table_name='cloud_projects')
    op.drop_index(op.f('ix_cloud_projects_cloud_provider'), table_name='cloud_projects')
    op.drop_index('idx_cloud_projects_tenant_enabled', table_name='cloud_projects')
    op.drop_index('idx_cloud_projects_provider_enabled', table_name='cloud_projects')
    op.drop_table('cloud_projects')
    # ### end Alembic commands ###