"""Add is_enabled column to llm_providers

Revision ID: c0770f67ed65
Revises: 0001
Create Date: 2025-08-29 19:33:21.806441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0770f67ed65'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_providers', sa.Column('is_enabled', sa.Boolean(), nullable=False))
    op.create_index('idx_llm_providers_enabled', 'llm_providers', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_llm_providers_is_enabled'), 'llm_providers', ['is_enabled'], unique=False)
    op.drop_index('idx_tenants_active', table_name='tenants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_tenants_active', 'tenants', ['is_active'], unique=False)
    op.drop_index(op.f('ix_llm_providers_is_enabled'), table_name='llm_providers')
    op.drop_index('idx_llm_providers_enabled', table_name='llm_providers')
    op.drop_column('llm_providers', 'is_enabled')
    # ### end Alembic commands ###