{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "audit-service.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "audit-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "audit-service.fullname" . }}-role
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "audit-service.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "audit-service.fullname" . }}-rolebinding
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "audit-service.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "audit-service.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "audit-service.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
{{- end }}
