# Development environment values
global:
  environment: development

image:
  tag: dev
  frontend:
    tag: dev

app:
  replicas:
    backend: 1
    frontend: 1
    worker: 1
    alerting: 1
    events: 1

namespace:
  name: audit-service-dev

backend:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  env:
    ENVIRONMENT: "development"
    LOG_LEVEL: "DEBUG"
    DATABASE_TYPE: "postgresql"
    BIGQUERY_DATASET: "audit_logs_dev"
    BIGQUERY_TABLE: "audit_events_dev"

frontend:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

worker:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

alerting:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  env:
    ENVIRONMENT: "development"
    LOG_LEVEL: "DEBUG"
    ALERTING_API_KEY: "dev-api-key-123"

events:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  env:
    ENVIRONMENT: "development"
    LOG_LEVEL: "DEBUG"
    EVENTS_API_KEY: "dev-events-api-key-123"

hpa:
  backend:
    enabled: false
  frontend:
    enabled: false
  alerting:
    enabled: false
  events:
    enabled: false

ingress:
  enabled: false

resources:
  quota:
    enabled: false
  limits:
    enabled: false

monitoring:
  enabled: false
